apiVersion: v1
kind: Secret
metadata:
  name: {{ include "happy-k8s.envSecretName" . }}
  labels:
    {{- include "happy-k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.credentials.gitPat }}
  GIT_PAT: {{ .Values.credentials.gitPat | quote }}
  {{- end }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
