{{- if or .Values.happy.accessKey .Values.happy.settings }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "happy-k8s.fullname" . }}-happy
  labels:
    {{- include "happy-k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.happy.accessKey }}
  access.key: |
{{ .Values.happy.accessKey | indent 4 }}
  {{- end }}
  {{- if .Values.happy.settings }}
  settings.json: |
{{ .Values.happy.settings | indent 4 }}
  {{- end }}
{{- end }}
