{{- if or .Values.happy.accessKey .Values.happy.settings }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "happy-k8s.fullname" . }}-happy
  labels:
    {{- include "happy-k8s.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.happy.accessKey }}
  access.key: |
    {{- if kindIs "string" .Values.happy.accessKey }}
{{ .Values.happy.accessKey | indent 4 }}
    {{- else }}
{{ .Values.happy.accessKey | toJson | indent 4 }}
    {{- end }}
  {{- end }}
  {{- if .Values.happy.settings }}
  settings.json: |
    {{- if kindIs "string" .Values.happy.settings }}
{{ .Values.happy.settings | indent 4 }}
    {{- else }}
{{ .Values.happy.settings | toJson | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
